### PR TITLE
fmt & clippy

### PR DESCRIPTION
**Pull request by Xiphoseer**
This PR runs `cargo fmt` and fixes all but one `cargo clippy` problem.

The issue with that last one ist that it is essentially a case for <https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary>, where you can cause undefined behavior by assuming a `impl std::io::Read` initializes a byte slice but you have a noticable performance regression if you don't and zero-initialize it. That has two possible solutions:

1. Use the nightly `read_buf` APIs
2. Just zero-init it, because it's just in `impl GmParam for Vec<u8>`

which is why I left it out of this PR

### CODE REVIEW

**Comment by lcdr** [comment]
Gonna close this for now since as discussed the automated tools have some issues, this is in general not a bad idea but i'd rather do it manually.

**Comment by enteryournamehere** [comment]
What are the problematic issues the automated tools have?
I quite like being able to use `cargo fmt` to quickly clean up my code and ensure consistency with the existing codebase. Could some of the concerns be resolved by [configuring rustfmt](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md) to better match your preferred style?

**Comment by lcdr** [comment]
fmt messed up some manual alignments I had in place, e.g.
test

**Comment by enteryournamehere** [comment]
Seems easy enough to avoid with a few `#[rustfmt::skip]` attributes - I've added those where you manually aligned things and configured rustfmt to use tabs for indentation.
What do you think?
Compare: https://github.com/lcdr/lu_packets/compare/master...enteryournamehere:lu_packets:d52fb4e
And these are the additional changes when reordering of imports and modules isn't turned off: https://github.com/enteryournamehere/lu_packets/commit/51ae4fea788bac76f74f313907e2098210484292

**Comment by lcdr** [comment]
Ah, that's good to know. I think with this it'd be worth a try again - IIRC what annoyed me was mostly the changes that clippy made, less the ones by rustfmt. I still don't like the idea of a bot shifting my code around, but with this repo now actually getting PRs from people (thank you for those!) I can see the advantage of an agreed upon standard for formatting in this repo.

One thing I still don't particularly like are the line breaks introduced to break up long lines - I'm of the opinion that line length should be up to everyone via the editor word-wrapping when lines are overflowing. It also seems to mostly do that on imports, which I don't find particularly useful to wrap in any case - in Rust these are more or less managed by the compiler anyway. If you could turn that off that'd be great.

With that said, I'd have no issues with approving a PR that does a rustfmt with that taken into account. If that PR (or a later one) also added a rustfmt pass to the CI, that'd be even better, but that's optional.

In principle I have nothing against checks on import and module ordering either, but the ordering enforced should be easily understandable and manually doable. I try to use alphabetical ordering on names and hierarchical ordering of modules in order of std, third-party crates, higher-level same crate imports, super, self. Unfortunately the ordering rustfmt uses is not readily apparent to me, e.g. it sorts `
use endio::{Deserialize, LERead, LEWrite, Serialize, LE};` which is neither alphabetical nor asciibetical, no idea how it arrived at this. The ordering for modules also seems to run counter to the way I usually do it. Would be nice to know what rustfmts sorting function is here and if there is a way to configure it. However if that's resolved I'd be open to a PR adding import and module ordering to the formatting pass.

**Comment by enteryournamehere** [comment]
> Unfortunately the ordering rustfmt uses is not readily apparent to me, e.g. it sorts `use endio::{Deserialize, LERead, LEWrite, Serialize, LE};` which is neither alphabetical nor asciibetical, no idea how it arrived at this.

Thought this was weird too so I looked into it, apparently `LE` comes last because its name is determined as UPPER_SNAKE_CASE while the others are CamelCase, see the responsible code here: https://github.com/rust-lang/rustfmt/blob/master/src/imports.rs#L908. According to the standard naming convention it's [supposed to be](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#fine-points) written as `Le`, along with `LeWrite` etc, but I can certainly understand if you'd rather keep the names like they are now.

That does mean that [`reorder_imports`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#reorder_imports) will need to stay off unless you're OK with having `LE` at the end. And [`group_imports`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#group_imports) could in theory be set to `StdExternalCrate` just fine, but it actually also reorders the imports themselves even with `reorder_imports` turned off.

**Pull request closed without merging**
